### PR TITLE
[WIP]Translate Part1

### PR DESCRIPTION
**Pull request by neighborhood999**
need check translate.

### CODE REVIEW

**Comment by AriaFallah** [comment]
This is pretty amazing, but the only problem I see with it is that it seems to be directly changing my english files. Would it be possible to put all your work into a separate folder?

**Comment by neighborhood999** [comment]
@AriaFallah You are right！Sorry, I didn't think that. I will add new folder put my translate file, Thanks.

**Comment by AriaFallah** [comment]
@neighborhood999 no worries! Thanks for making this.

**Comment by neighborhood999** [comment]
@AriaFallah Sorry！XD. It's my wrong haha. I will open this PR on my fork repo :p
If I finish this work, I will send new PR for you, so I close this.

**Comment by neighborhood999** [comment]
@AriaFallah thanks your tutorial！I think this really helpful, so I want to translate for my friends...etc for learning.

**Pull request closed without merging**
