### PR TITLE
'eslint-config-airbnb/base' is deprecated. Use eslint-config-airbnb-base instead.

### PR DESCRIPTION
**Pull request by zirho**
'eslint-config-airbnb/base' is deprecated. 
Use eslint-config-airbnb-base instead.
Checkout https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnbbase

### CODE REVIEW

**Comment by AriaFallah** [comment]
Thanks for the catch. I stopped using the `airbnb` config in favor of my own so I had no idea.

**Comment by zirho** [comment]
Thank you for merging it 👍 
really awesome tutorial!

**Comment by zirho** [comment]
@AriaFallah 
Is there any way I can take a sneak peek for you eslint config?
Thanks

**Comment by AriaFallah** [comment]
Yep! I made it by looking through the eslint rules 1 by 1, and deciding which one of those I wanted a while ago. It took a few hours, but I think it was worth it because I got full control of what I wanted in my code.

https://github.com/AriaFallah/eslint-config-aria/blob/master/index.js

**Pull request merged**
