### PR TITLE
Change to install eslint on local to match the scope plugin package installed

### PR DESCRIPTION
**Pull request by zirho**
if they are installed in different scope, you get errors like below

```
Cannot find module 'eslint-config-airbnb-base'
Referenced from: /Projects/web-app/.eslintrc
Error: Cannot find module 'eslint-config-airbnb-base'
```

And install eslint-cli to access it just like globally installed
package.

### CODE REVIEW

**Comment by AriaFallah** [comment]
Hmmm this will only happen if you try to run eslint yourself instead of running it using

```
npm run lint
```

from your `package.json` right? (if I'm wrong about that ignore what follows).

Perhaps instead of installing eslint globally without mentioning why, I could add some more details about what will happen if you try to run eslint globally, and why it won't work. In that case, I'd close your PR, and make the additions myself since they're a bit more complex. Does that sound good?

**Comment by zirho** [comment]
I just checked real quick. 
I think it happens even when you use npm scripts.
I'm not sure if it is because of NVM tho.

I'm on node 4.3.1 with NVM.

**Comment by AriaFallah** [comment]
@zirho haha rip. I'll double check that it fails even with the NPM scripts, and then I'll look into merging this PR. Currently the only reason I haven't merged it is that I need a good explanation for why the `npm install` is required other than "it breaks if you don't have it"

**Comment by zirho** [comment]
No matter what I PRed, just go for what you think it fits for it.
I'm just glad that I pointed out that!

thanks

**Comment by AriaFallah** [comment]
Hmmm it works for me with `npm run lint`...not sure what the difference between us is. I updated the `example1` repo. Could you try cloning this again, and running `npm run lint` in there? (after `npm install` of course)

**Comment by zirho** [comment]
Sure, I'm on it.

**Comment by zirho** [comment]
NVM  0.29.0
node 4.3.1
npm 3.9.0
eslint 2.12.0

As I said I am using NVM.
I uninstalled global eslint and eslint-cli 

Then 
I installed eslint
I installed packages in the `example1`

```
npm un -g eslint eslint-cli
npm i -g eslint
npm i 
```

and I get

```
Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-babel". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-babel is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-babel@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I'm also using `zsh`
my local user name is zirho6

```
echo $PATH
/Users/zirho6/.rvm/gems/ruby-2.2.4/bin:/Users/zirho6/.rvm/gems/ruby-2.2.4@global/bin:/Users/zirho6/.rvm/rubies/ruby-2.2.4/bin:/Users/zirho6/.nvm/versions/node/v4.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/zirho6/bin:/Users/zirho6/.fzf/bin:/Users/zirho6/.rvm/bin
```

```
which eslint
/Users/zirho6/.nvm/versions/node/v4.3.1/bin/eslint
```

Hope this helps to figure out.

**Comment by AriaFallah** [comment]
Hmmm alright. I'll look more into this later today. Perhaps it'll lead to me finally updating the whole tutorial 😛 . If one part is broken, I might as well fix the whole entire thing.

**Comment by ghost** [comment]
@AriaFallah What is the status of this PR? Updates to this tutorial are very much needed.

**Comment by AriaFallah** [comment]
@AxFx This exact PR I might as well merge since it's not a big deal.

As for on the larger scale, I've been really busy 😕 so it's been hard to put work into this especially since I'm not doing much frontend work.

But since I will be updating it eventually™, are there any parts in particular that you'd like to see updated?

**Pull request merged**
